
export const STRINGS = {
  appName: 'NeL',
  startChat: 'بدء المحادثة',
  searching: 'جاري البحث عن غريب...',
  connected: 'أنت تتحدث الآن مع غريب!',
  typeMessage: 'اكتب رسالة...',
  next: 'التالي',
  stop: 'إنهاء',
  reallyStop: 'هل أنت متأكد؟',
  newChat: 'محادثة جديدة',
  activeNow: 'نشط الآن',
  welcomeTitle: 'دردشة عشوائية',
  welcomeSubtitle: 'تحدث مع الغرباء!',
  emptyState: 'اضغط على الزر أدناه للبحث عن شخص للتحدث معه.',
  onlineUsers: 'شخص متصل الآن',
  startSearch: 'ابدأ البحث',
  matchPreferences: 'ما هي اهتماماتك؟',
  random: 'عشوائي',
  global: 'عالمي',
  addInterestPlaceholder: 'أضف اهتماماً (مثلاً: كرة قدم، أنمي)...',
  textChat: 'دردشة نصية',
  videoChat: 'فيديو',
  interestsLabel: 'الاهتمامات (اختياري)',
  commonInterests: 'أنتما تشتركان في: ',
  stranger: 'غريب',
};
